# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b8335a66-f76b-47a3-908a-a132f3df68bb";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b8335a66-f76b-47a3-908a-a132f3df68bb";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/b8335a66-f76b-47a3-908a-a132f3df68bb";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/b8335a66-f76b-47a3-908a-a132f3df68bb";
      fsType = "btrfs";
      options = [ "subvol=srv" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b8335a66-f76b-47a3-908a-a132f3df68bb";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CDFA-5654";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a10d9f5d-ceac-4400-9b1d-9ed9c44fe437"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
